developer_portal/blog/urls.py
# Override Zinnia's default urlconf to filter listings by language/category

"""Urls for the Zinnia archives"""
from django.conf.urls import url
from django.conf.urls import include
from django.conf.urls import patterns

from zinnia.urls import _
from developer_portal.blog.views import MultiLangEntryDay
from developer_portal.blog.views import MultiLangEntryWeek
from developer_portal.blog.views import MultiLangEntryYear
from developer_portal.blog.views import MultiLangEntryMonth
from developer_portal.blog.views import MultiLangEntryToday
from developer_portal.blog.views import MultiLangEntryIndex

urlpatterns = patterns(
    '',
    url(_(r'^feeds/'), include('zinnia.urls.feeds')),
    url(_(r'^tags/'), include('zinnia.urls.tags')),
    url(_(r'^authors/'), include('zinnia.urls.authors')),
    url(_(r'^categories/'), include('zinnia.urls.categories')),
    url(_(r'^search/'), include('zinnia.urls.search')),
    url(_(r'^random/'), include('zinnia.urls.random')),
    url(_(r'^sitemap/'), include('zinnia.urls.sitemap')),
    url(_(r'^trackback/'), include('zinnia.urls.trackback')),
    url(_(r'^comments/'), include('zinnia.urls.comments')),
    url(r'^', include('zinnia.urls.entries')),

    url(r'^$',
        MultiLangEntryIndex.as_view(),
        name='entry_archive_index'),
    url(_(r'^page/(?P<page>\d+)/$'),
        MultiLangEntryIndex.as_view(),
        name='entry_archive_index_paginated'),

    url(r'^(?P<year>\d{4})/$',
        MultiLangEntryYear.as_view(),
        name='entry_archive_year'),
    url(_(r'^(?P<year>\d{4})/page/(?P<page>\d+)/$'),
        MultiLangEntryYear.as_view(),
        name='entry_archive_year_paginated'),

    url(_(r'^(?P<year>\d{4})/week/(?P<week>\d+)/$'),
        MultiLangEntryWeek.as_view(),
        name='entry_archive_week'),
    url(_(r'^(?P<year>\d{4})/week/(?P<week>\d+)/page/(?P<page>\d+)/$'),
        MultiLangEntryWeek.as_view(),
        name='entry_archive_week_paginated'),

    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/$',
        MultiLangEntryMonth.as_view(),
        name='entry_archive_month'),
    url(_(r'^(?P<year>\d{4})/(?P<month>\d{2})/page/(?P<page>\d+)/$'),
        MultiLangEntryMonth.as_view(),
        name='entry_archive_month_paginated'),

    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/$',
        MultiLangEntryDay.as_view(),
        name='entry_archive_day'),
    url(_(r'^(?P<year>\d{4})/(?P<month>\d{2})/'
          '(?P<day>\d{2})/page/(?P<page>\d+)/$'),
        MultiLangEntryDay.as_view(),
        name='entry_archive_day_paginated'),

    url(_(r'^today/$'),
        MultiLangEntryToday.as_view(),
        name='entry_archive_today'),
    url(_(r'^today/page/(?P<page>\d+)/$'),
        MultiLangEntryToday.as_view(),
        name='entry_archive_today_paginated'),

    url(r'^', include('zinnia.urls.shortlink')),
    url(r'^', include('zinnia.urls.quick_entry')),
    url(r'^', include('zinnia.urls.capabilities')),
)

developer_portal/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from developer_portal.views import login_failure, listen_for_login

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^logout$', 'developer_portal.views.site_logout', name='logout')
)

urlpatterns += patterns(
    'django_openid_auth.views',
    url(r'^openid/login/$', 'login_begin', name='openid-login',
        kwargs={'render_failure': login_failure}),
    url(r'^openid/complete/$', 'login_complete', name='openid-complete',
        kwargs={'render_failure': login_failure}),
    url(r'^openid/logo.gif$', 'logo', name='openid-logo'),
    url(r'^api/service/', include('service.urls', namespace='rest_framework')),
    url(r'^api/', include('api_docs.urls', namespace='api_docs')),
)
listen_for_login()

urlpatterns += i18n_patterns('',
    url(r'^blog/', include('developer_portal.blog.urls', namespace='zinnia')),
    url(r'^blog/comments/', include('django_comments.urls')),
)

urlpatterns += i18n_patterns('',
    url(r'^search/', 'developer_portal.views.search', name='search'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^', include('cms.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += patterns('webapp_creator.views',
                       url(r'^webapp-generator/$', 'webapp', name='webapp'),
)

urlpatterns += patterns('translations_dashboard.views',
                       url(r'^translations-dashboard/$', 'translations_dashboard', name='translations_dashboard'),
)

service/urls.py
from django.conf.urls import url, patterns, include
from rest_framework import routers
from service.views import *

# Routers provide an easy way of automatically determining the URL conf
router = routers.DefaultRouter()
router.register(r'elements', ElementViewSet, base_name='element-list')
router.register(r'pages', PageViewSet, base_name='page-list')
router.register(r'namespaces', NamespaceViewSet, base_name='namespace-list')
router.register(r'sections', SectionViewSet, base_name='section-list')
router.register(r'versions', VersionViewSet, base_name='version-list')
router.register(r'languages', LanguageViewSet, base_name='language-list')
router.register(r'topics', TopicViewSet, base_name='topic-list')


# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browseable API.
urlpatterns = patterns('',
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
)

templates/zinnia/_entry_detail_base.html
{% load i18n zinnia %}
<article class="row no-border no-padding-bottom post {% if object.featured %} featured{% endif %}">
    <div class="eight-col">
        {% block entry-header %}
        <header>
            {% block entry-title %}
            <h1>
                <a href="{{ object.get_absolute_url }}" title="{{ object.title }}" rel="bookmark">{{ object.title|widont }}</a>
            </h1>
            {% endblock entry-title %}
        </header>
        {% endblock entry-header %}
        {% block entry-body %}
            {# Post image #}
            {% block entry-image %}
                {% if object.image %}
                {% if continue_reading %}
                <a href="{{ object.get_absolute_url }}" title="{{ object.title }}" rel="bookmark">
                {% endif %}
                    <img class="post-image" src="{{ object.image.url }}" alt="{{ object.title }}" class="left" />
                {% if continue_reading %}
                </a>
                {% endif %}
                {% endif %}
            {% endblock entry-image %}
            {# Post content #}
            {% block entry-content %}
                {{ object_content|safe }}
            {% endblock entry-content %}
            {% block continue-reading %}
                {% if continue_reading and object_content.has_more %}
                <p class="continue-reading">
                    <a href="{{ object.get_absolute_url }}" title="{% blocktrans with object=object.title percent=object_content.remaining_percent|floatformat:0 %}{{ percent }}% of {{ object }} still remains to read.{% endblocktrans %}" rel="bookmark">{% trans "Continue reading" %}</a>
                </p>
                {% endif %}
            {% endblock continue-reading %}
        {% endblock entry-body %}
    </div>
    <div class="prepend-one two-col append-one last-col">
        {% block entry-info %}
        <aside>
            {% block entry-authors %}
                <p class="author">
                {% with authors=object.authors.all %}
                {% if authors|length %}
                {% for author in authors %}
                <span class="vcard"><a href="{{ author.get_absolute_url }}" class="fn url{% if not author.get_full_name %} nickname{% endif %}" rel="author" title="{% blocktrans %}Show all {{ author }}'s entries{% endblocktrans %}">{{ author }}</a></span>{% if not forloop.last %}, {% endif %}
                {% endfor %}
                {% else %}
                {% trans "Written on" %}
                {% endif %}
                {% endwith %}
                </p>
            {% endblock entry-authors %}
            {% block entry-published %}
            <p class="post-date" title="{{ object.creation_date|date:"c" }}">
                {{ object.creation_date|date:"DATE_FORMAT" }}
            </p>
            {% endblock entry-published %}
            {% block entry-tags %}
            <p class="entry-tags">
                {% trans "Filed under:" %}
                {% for tag in object.tags_list %}
                <a href="{% url 'zinnia:tag_detail' tag %}" title="{% blocktrans %}Show all entries tagged by {{ tag }}{% endblocktrans %}" rel="tag">{{ tag }}</a>
                {% empty %}
                <span>{% trans "No tags" %}</span>
              {% endfor %}
            </p>
            {% endblock entry-tags %}
        </aside>
        {% endblock entry-info %}
    </div>
</article>

templates/zinnia/author_list.html
{% extends "zinnia/base.html" %}
{% load i18n %}

{% block meta-description %}{% trans "Author list" %}{% endblock meta-description %}

{% block title %}{% trans "Authors" %} | {{ block.super }}{% endblock title%}

{% block body-class %}author-list{% endblock body-class %}

{% block content %}
    <div class="row">
        <h1>{% trans "Author list" %}</h1>
    </div>
    <div class="row no-border">
        <ul>
            {% for object in object_list %}
            <li class="vcard">
                <a href="{{ object.get_absolute_url }}"
                title="{% blocktrans with author=object %}Show all {{ author }}'s entries{% endblocktrans %}"
                class="fn url{% if not author.get_full_name %} nickname{% endif %}">{{ object }}</a>
                {% blocktrans count entry_count=object.count_entries_published %}{{ entry_count }} entry{% plural %}{{ entry_count }} entries{% endblocktrans %}
            </li>
            {% empty %}
            <li>
                {% trans "No authors yet." %}
            </li>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}

templates/zinnia/base.html
{% extends "base.html" %}
{% load zinnia i18n %}
{% load cms_tags sekizai_tags menu_tags static %}

{% block meta-keywords %}{% get_tags as entry_tags %}{{ entry_tags|join:", "}}{% endblock meta-keywords %}

{% block meta %}
    <meta name="generator" content="Zinnia {{ ZINNIA_VERSION }}" />
{% endblock meta %}

{% block link %}
    <link rel="index" href="{% url 'zinnia:entry_archive_index' %}" />
    <link rel="author" type="text/plain" href="{% url 'zinnia:humans' %}" />
    <link rel="EditURI" type="application/rsd+xml" href="{% url 'zinnia:rsd' %}" />
    <link rel="wlwmanifest" type="application/wlwmanifest+xml" href="{% url 'zinnia:wlwmanifest' %}" />
    <link rel="search" type="application/opensearchdescription+xml" title="Zinnia's Weblog" href="{% url 'zinnia:opensearch' %}" />
    <link rel="alternate" type="application/rss+xml" title="{% trans "RSS Feed of latest entries" %}" href="{% url 'zinnia:entry_latest_feed' %}" />
    <link rel="alternate" type="application/rss+xml" title="{% trans "RSS Feed of latest discussions" %}" href="{% url 'zinnia:discussion_latest_feed' %}" />
    {% get_archives_entries "zinnia/tags/entries_archives_link.html" %}
{% endblock link %}

{% block closure %}
<script type='text/javascript' src='{% static "developer_portal/syntaxhighlighter3/scripts/shCore.js?ver=3.0.83"  %}c'></script>
<script type='text/javascript' src='{% static "developer_portal/syntaxhighlighter3/scripts/shAutoloader.js?ver=3.0.83c" %}'></script>
<script type='text/javascript'>
    (function(){
	    var corecss = document.createElement('link');
	    var themecss = document.createElement('link');
	    var corecssurl = "{% static "developer_portal/syntaxhighlighter3/styles/shCore.css?ver=3.0.83c" %}";
	    if ( corecss.setAttribute ) {
			    corecss.setAttribute( "rel", "stylesheet" );
			    corecss.setAttribute( "type", "text/css" );
			    corecss.setAttribute( "href", corecssurl );
	    } else {
			    corecss.rel = "stylesheet";
			    corecss.href = corecssurl;
	    }
	    document.getElementsByTagName("head")[0].insertBefore( corecss, document.getElementById("syntaxhighlighteranchor") );
	    var themecssurl = "{% static "developer_portal/syntaxhighlighter3/styles/shThemeDefault.css?ver=3.0.83c" %}";
	    if ( themecss.setAttribute ) {
			    themecss.setAttribute( "rel", "stylesheet" );
			    themecss.setAttribute( "type", "text/css" );
			    themecss.setAttribute( "href", themecssurl );
	    } else {
			    themecss.rel = "stylesheet";
			    themecss.href = themecssurl;
	    }
	    //document.getElementById("syntaxhighlighteranchor").appendChild(themecss);
	    document.getElementsByTagName("head")[0].insertBefore( themecss, document.getElementById("syntaxhighlighteranchor") );
    })();
    SyntaxHighlighter.config.strings.expandSource = '+ expand source';
    SyntaxHighlighter.config.strings.help = '?';
    SyntaxHighlighter.config.strings.alert = 'SyntaxHighlighter\n\n';
    SyntaxHighlighter.config.strings.noBrush = 'Can\'t find brush for: ';
    SyntaxHighlighter.config.strings.brushNotHtmlScript = 'Brush wasn\'t configured for html-script option: ';
    SyntaxHighlighter.defaults['pad-line-numbers'] = false;
    SyntaxHighlighter.defaults['toolbar'] = false;
    SyntaxHighlighter.autoloader(
      'js jscript javascript  {% static "developer_portal/syntaxhighlighter3/scripts/" %}shBrushJScript.js',
      'c cpp                  {% static "developer_portal/syntaxhighlighter3/scripts/" %}shBrushCpp.js',
      'xml html               {% static "developer_portal/syntaxhighlighter3/scripts/" %}shBrushXml.js',
      'bash                   {% static "developer_portal/syntaxhighlighter3/scripts/" %}shBrushBash.js',
      'python                 {% static "developer_portal/syntaxhighlighter3/scripts/" %}shBrushPython.js'
    );
    SyntaxHighlighter.all();
</script>

{% endblock closure %}

templates/zinnia/category_list.html
{% extends "zinnia/base.html" %}

{% load i18n %}

{% block meta-description %}{% trans "Category list" %}{% endblock meta-description %}

{% block title %}{% trans "Categories" %} | {{ block.super }}{% endblock title%}

{% block body-class %}category-list{% endblock body-class %}

{% block content %}
    <div class="row">
        <h1>{% trans "Category list" %}</h1>
    </div>
    <div class="row no-border">
        <ul>
            {% for object in object_list %}
            <li>
                <a href="{{ object.get_absolute_url }}" title="{% blocktrans with category=object %}Show all entries in {{ category }}{% endblocktrans %}">{{ object }}</a>
                {% blocktrans count entry_count=object.count_entries_published %}{{ entry_count }} entry{% plural %}{{ entry_count }} entries{% endblocktrans %}
                {% if object.description %}<p>{{ object.description|striptags|safe }}</p>{% endif %}
            </li>
            {% empty %}
            <li>
                {% trans "No categories yet." %}
            </li>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}

templates/zinnia/entry_detail_base.html
{% extends "zinnia/base.html" %}
{% load i18n comments zinnia %}
{% load cycle from future %}

{% block title %}{{ object.title }} | {{ block.super }}{% endblock title%}

{% block meta-description %}{{ object.excerpt|safe }}{% endblock meta-description %}

{% block meta-keywords %}{% if object.tags %}{{ object.tags }}{% else %}{{ block.super }}{% endif %}{% endblock meta-keywords %}

{% block link %}
  {{ block.super }}
  {% with previous_entry=object.previous_entry %}{% if previous_entry %}
  <link rel="prev" title="{{ previous_entry.title }}" href="{{ previous_entry.get_absolute_url }}" />
  {% endif %}{% endwith %}
  {% with next_entry=object.next_entry %}{% if next_entry %}
  <link rel="next" title="{{ next_entry.title }}" href="{{ next_entry.get_absolute_url }}" />
  {% endif %}{% endwith %}
  <link rel="shortlink" href="{{ object.short_url }}" />
  <link rel="canonical" href="{{ object.get_absolute_url }}" />
  {% with year=object.creation_date|date:"Y" month=object.creation_date|date:"m" day=object.creation_date|date:"d" %}
  <link rel="alternate" type="application/rss+xml" title="{% trans "RSS Feed of discussions on" %} '{{ object.title }}'"
        href="{% url 'zinnia:entry_discussion_feed' year month day object.slug %}" />
  <link rel="alternate" type="application/rss+xml" title="{% trans "RSS Feed of comments on" %} '{{ object.title }}'"
        href="{% url 'zinnia:entry_comment_feed' year month day object.slug %}" />
  <link rel="alternate" type="application/rss+xml" title="{% trans "RSS Feed of pingbacks on" %} '{{ object.title }}'"
        href="{% url 'zinnia:entry_pingback_feed' year month day object.slug %}" />
  <link rel="alternate" type="application/rss+xml" title="{% trans "RSS Feed of trackbacks on" %} '{{ object.title }}'"
        href="{% url 'zinnia:entry_trackback_feed' year month day object.slug %}" />
  {% endwith %}
{% endblock link %}

{% block body-class %}entry entry-{{ object.pk }}{% if object.featured %} featured{% endif %} year-{{ object.creation_date|date:"Y" }} month-{{ object.creation_date|date:"m" }} week-{{ object.creation_date|date:"W" }} day-{{ object.creation_date|date:"d" }}{% endblock body-class %}

{% block content %}
    {% block entry-content %}
        {% include object.content_template with object_content=object.html_content %}
    {% endblock entry-content %}

    {# Post Comments #}
    {% block entry-comments %}
        <div id="comments" class="row no-border no-padding-bottom">
            <h2 class="eight-col">{% trans "Comments" %}</h2>
            <div class="eight-col">
                {% if object.comment_count %}
                {% with comment_list=object.comments %}

                {% block comments-loop %}
                <ol id="comment-list" class="eight-col">
                {% for comment in comment_list %}
                    <li id="comment-{{ comment.pk }}-by-{{ comment.user_name|slugify }}" class="eight-col comment vcard {% cycle box1,box2 %}{% if comment.user %} authenticated-comment{% if comment.user.is_staff %} staff-comment{% endif %}{% if comment.user.is_superuser %} superuser-comment{% endif %}{% endif %}">
                        <div class="two-col">
                            {% block comment-image %}
                                <span class="image-wrap">
                                    <img src="{% get_gravatar comment.email 60 "G" %}" class="gravatar photo" alt="{{ comment.name }}" />
                                </span>
                            {% endblock comment-image %}

                            {% block comment-info %}
                                {% if comment.url %}
                                    <cite>
                                        <a href="{{ comment.url }}" rel="external nofollow" class="fn url">{{ comment.name }}</a>
                                    </cite>
                                {% else %}
                                    <cite class="fn">{{ comment.name }}</cite>
                                {% endif %}
                                    <time class="comment-published" title="{{ comment.submit_date|date:"c" }}">{{ comment.submit_date|date:"SHORT_DATETIME_FORMAT" }}</time>
                            {% endblock comment-info %}
                        </div>
                        <div class="six-col last-col">
                        {% block comment-content %}
                            {{ comment.comment|linebreaks }}
                        {% endblock comment-content %}
                        </div>
                    </li>
                {% endfor %}
                </ol>
                {% endblock comments-loop %}

                {% endwith %}
                {% if not object.comments_are_open %}
                <p>{% trans "Comments are closed." %}</p>
                {% endif %}
                {% else %}
                {% if object.comments_are_open %}
                <p>{% trans "No comments yet." %}</p>
                {% else %}
                <p>{% trans "Comments are closed." %}</p>
                {% endif %}
                {% endif %}
            </div>
    {% endblock entry-comments %}

    {% block entry-comments-form %}
    {% if object.comments_are_open %}
            <h2 class="eight-col">{% trans "Add your comment" %}</h2>
            <div class="eight-col">
                {% render_comment_form for object %}
            </div>
        </div>
    {% endif %}
    {% endblock entry-comments-form %}
{% endblock content %}

{% block admin-tools %}
{% if perms.zinnia.change_entry %}
<li>
  <a href="{% url 'admin:zinnia_entry_change' object.pk %}" title="{% trans "Edit the entry" %}">
    {% trans "Edit the entry" %}
  </a>
</li>
{% endif %}
{% endblock admin-tools %}

templates/zinnia/entry_list.html
{% extends "zinnia/base.html" %}
{% load i18n zinnia %}

{% block meta-description %}{% trans "Latest entries for" %} {% if category %}{% trans "the category" %} {{ category }}{% if category.description %}: {{ category.description|striptags|safe }}{% endif %}{% endif %}{% if tag %}{% trans "the tag" %} {{ tag }}{% endif %}{% if author %}{% trans "the author" %} {{ author }}{% endif %}{% endblock meta-description %}

{% block meta-description-page %}{% if page_obj %}{% ifnotequal page_obj.number 1 %} {% trans "page" %} {{ page_obj.number }}{% endifnotequal %}{% endif %}{% endblock meta-description-page %}

{% block link %}
  {{ block.super }}
  {% if category %}
    <link rel="alternate" type="application/rss+xml" title="{% trans "RSS Feed" %} {{ category }}" href="{% url 'zinnia:category_feed' category.tree_path %}" />
  {% endif %}
  {% if tag %}
    <link rel="alternate" type="application/rss+xml" title="{% trans "RSS Feed" %} {{ tag }}" href="{% url 'zinnia:tag_feed' tag.name %}" />
  {% endif %}
  {% if author %}
    <link rel="alternate" type="application/rss+xml" title="{% trans "RSS Feed" %} {{ author }}" href="{% url 'zinnia:author_feed' author.get_username %}" />
  {% endif %}
{% endblock link %}

{% block title %}{% if category %}{% trans "Category" %} {{ category }}{% endif %}{% if tag %}{% trans "Tag" %} {{ tag }}{% endif %}{% if author %}{% trans "Author" %} {{ author }}{% endif %}{% endblock title %}

{% block title-page %}{% if page_obj %}{% ifnotequal page_obj.number 1 %} - {% trans "Page" %} {{ page_obj.number }}{% endifnotequal %}{% endif %}{% endblock title-page %}

{% block body-class %}entry-list{% if page_obj %} paginated page-{{ page_obj.number }}{% endif %}{% if category %} category category-{{ category.slug }}{% endif %}{% if tag %} tag tag-{{ tag|slugify }}{% endif %}{% if author %} author author-{{ author|slugify }}{% endif %}{% endblock body-class %}

{% block content %}

{% block content-title %}
    {% if category %}
    <div class="row">
        <h1>{% blocktrans %}Category archives: {{ category }}{% endblocktrans %}</h1>
        {% if category.description %}
        <p>{{ category.description|striptags|safe }}</p>
        {% endif %}
    </div>
    {% endif %}

    {% if tag %}
    <div class="row">
        <h1>{% blocktrans %}Tag archives: {{ tag }}{% endblocktrans %}</h1>
    </div>
    {% endif %}

    {% if author %}
    <div class="row">
        <h1>{% blocktrans %}Author archives: {{ author }}{% endblocktrans %}</h1>
    </div>
    {% endif %}
{% endblock content-title %}

{% block content-loop %}
<div class="post-list">
{% for object in object_list %}
  {% include object.content_template with object_content=object.html_preview continue_reading=1 %}
{% empty %}
  <p class="info">
    <a href="{% url 'admin:zinnia_entry_add' %}">{% trans "No entries yet." %}</a>
  </p>
{% endfor %}
</div>
{% endblock content-loop %}

{% block content-pagination %}
{% if is_paginated %}
  {% zinnia_pagination page_obj %}
{% endif %}
{% endblock content-pagination %}

{% endblock content %}

{% block admin-tools %}
  {% if category and perms.zinnia.change_category %}
  <li>
    <a href="{% url 'admin:zinnia_category_change' category.pk %}" title="{% trans "Edit the category" %}">
      {% trans "Edit the category" %}
    </a>
  </li>
  {% endif %}
  {% if tag and perms.tagging.change_tag %}
  <li>
    <a href="{% url 'admin:tagging_tag_change' tag.pk %}" title="{% trans "Edit the tag" %}">
      {% trans "Edit the tag" %}
    </a>
  </li>
  {% endif %}
  {% if author and perms.auth.change_user %}
  <li>
    <a href="{% url 'change'|user_admin_urlname author.pk %}" title="{% trans "Edit the author" %}">
      {% trans "Edit the author" %}
    </a>
  </li>
  {% endif %}
{% endblock admin-tools %}

templates/zinnia/tag_list.html
{% extends "zinnia/base.html" %}
{% load i18n %}

{% block meta-description %}{% trans "Tag list" %}{% endblock meta-description %}

{% block title %}{% trans "Tags" %} | {{ block.super }}{% endblock title%}

{% block body-class %}tag-list{% endblock body-class %}

{% block content %}
    <div class="row">
        <h1>{% trans "Tag list" %}</h1>
    </div>
    <div class="row no-border">
        <ul>
            {% for object in object_list %}
            <li>
                <a href="{% url 'zinnia:tag_detail' object %}"
                title="{% blocktrans with tag=object %}Show all entries tagged by {{ tag }}{% endblocktrans %}">{{ object }}</a>
                {% blocktrans count entry_count=object.count %}{{ entry_count }} entry{% plural %}{{ entry_count }} entries{% endblocktrans %}
            </li>
            {% empty %}
            <li>
            {% trans "No tags yet." %}
            </li>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}