api_docs/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = staticfiles_urlpatterns()


urlpatterns += patterns('',
   
    # REST framework
    url(r'^$', 'api_docs.views.overview', name='overview'),
    url(r'^(?P<topic_name>[\w\.-]+)/$', 'api_docs.views.topic_view', name='topic'),
    url(r'^(?P<topic_name>[\w\.-]+)/(?P<language_name>[\w\.-]+)/$', 'api_docs.views.language_view', name='language'),
    url(r'^(?P<topic_name>[\w\.-]+)/(?P<language_name>[\w\.-]+)/(?P<release_version>[\w\.-]+)/$', 'api_docs.views.version_view', name='version'),
    url(r'^(?P<topic_name>[\w\.-]+)/(?P<language_name>[\w\.-]+)/\+release/$', 'api_docs.views.release_version', name='release_version'),
    url(r'^(?P<topic_name>[\w\.-]+)/(?P<language_name>[\w\.-]+)/(?P<release_version>[\w\.-]+)/(?P<element_fullname>[\w\.\-\:]+)/$', 'api_docs.views.element_view', name='element'),
    
)

developer_portal/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from developer_portal.views import login_failure, listen_for_login

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^logout$', 'developer_portal.views.site_logout', name='logout')
)

urlpatterns += patterns(
    'django_openid_auth.views',
    url(r'^openid/login/$', 'login_begin', name='openid-login',
        kwargs={'render_failure': login_failure}),
    url(r'^openid/complete/$', 'login_complete', name='openid-complete',
        kwargs={'render_failure': login_failure}),
    url(r'^openid/logo.gif$', 'logo', name='openid-logo'),
    url(r'^api/service/', include('service.urls', namespace='rest_framework')),
    url(r'^api/', include('api_docs.urls', namespace='api_docs')),
)
listen_for_login()

urlpatterns += i18n_patterns('',
    url(r'^blog/', include('developer_portal.blog.urls', namespace='zinnia')),
    url(r'^blog/comments/', include('django_comments.urls')),
)

urlpatterns += i18n_patterns('',
    url(r'^search/', 'developer_portal.views.search', name='search'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^', include('cms.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += patterns('webapp_creator.views',
                       url(r'^webapp-generator/$', 'webapp', name='webapp'),
)

urlpatterns += patterns('translations_dashboard.views',
                       url(r'^translations-dashboard/$', 'translations_dashboard', name='translations_dashboard'),
)

service/urls.py
from django.conf.urls import url, patterns, include
from rest_framework import routers
from service.views import *

# Routers provide an easy way of automatically determining the URL conf
router = routers.DefaultRouter()
router.register(r'elements', ElementViewSet, base_name='element-list')
router.register(r'pages', PageViewSet, base_name='page-list')
router.register(r'namespaces', NamespaceViewSet, base_name='namespace-list')
router.register(r'sections', SectionViewSet, base_name='section-list')
router.register(r'versions', VersionViewSet, base_name='version-list')
router.register(r'languages', LanguageViewSet, base_name='language-list')
router.register(r'topics', TopicViewSet, base_name='topic-list')


# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browseable API.
urlpatterns = patterns('',
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
)

api_docs/models.py
from django.db import models

# Create your models here.

class Topic(models.Model):
    
    name = models.CharField(max_length=64)
    slug = models.CharField(max_length=64)
    
    def __unicode__(self):
        return self.name

class Language(models.Model):

    topic = models.ForeignKey(Topic)
    name = models.CharField(max_length=64)
    slug = models.CharField(max_length=64)

    current_version = models.ForeignKey('Version', blank=True, null=True, related_name='current_for_lang')
    development_version = models.ForeignKey('Version', blank=True, null=True, related_name='development_for_lang')

    def __unicode__(self):
        return self.topic.name +' '+self.name
    
class Version(models.Model):
    
    language = models.ForeignKey(Language, null=True)
    name = models.CharField(max_length=64)
    slug = models.CharField(max_length=64)

    def import_from(self, target_version):
        for section in target_version.section_set.all():
            self.section_set.add(section.clone())
            
    def __unicode__(self):
        return self.language.topic.name +' '+self.language.name +' '+self.name


class Section(models.Model):

    name = models.CharField(max_length=64)
    description = models.TextField(blank=True, null=True)
    topic_version = models.ForeignKey(Version)
    
    def __unicode__(self):
        return self.topic_version.language.topic.name +' '+ self.topic_version.language.name +' '+self.topic_version.name+', '+self.name

    def clone(self):
        new = Section(name=self.name, description=self.description, topic_version=self.topic_version)
        new.save()
        for namespace in self.namespace_set.all():
            new.namespace_set.add(namespace.clone(new))
            
        for element in self.element_set.all():
            if not element.namespace:
                element.section = new
                element.id = None
                element.save()
                new.element_set.add(element)

        for page in self.page_set.all():
            if not page.namespace:
                page.section = new
                page.id = None
                page.save()
                new.page_set.add(page)

        return new
        
    @property
    def topic(self):
        return self.topic_version.topic
        
    def has_namespaces(self):
        return self.namespace_set.count() > 0
    
    def has_free_elements(self):
        return self.element_set.filter(namespace=None).count() > 0
    
    def free_element_set(self):
        return self.element_set.filter(namespace=None)

    def has_free_pages(self):
        return self.page_set.filter(namespace=None).count() > 0
    
    def free_page_set(self):
        return self.page_set.filter(namespace=None)

class Namespace(models.Model):

    platform_section = models.ForeignKey(Section)
    name = models.CharField(max_length=64)
    display_name = models.CharField(max_length=64, blank=True, default='')

    data = models.TextField(blank=True, default='')
    source_file = models.CharField(max_length=128, blank=True, null=True)
    source_format = models.CharField(max_length=32, blank=True, null=True)

    class Meta:
        ordering = ('name',)

    def __unicode__(self):
        return u'%s' % self.name
        
    def clone(self, new_section):
        new = Namespace(name=self.name, display_name=self.display_name, data=self.data, source_file=self.source_file, source_format=self.source_format, platform_section=new_section)
        new.save()

        for element in self.element_set.all():
            element.section = new_section
            element.namespace = new
            element.id = None
            element.save()
            new.element_set.add(element)

        for page in self.page_set.all():
            page.section = new_section
            page.namespace = new
            page.id = None
            page.save()
            new.page_set.add(page)

        return new

    @property
    def display(self):
        if self.display_name:
            return self.display_name
        else:
            return self.name


class Element(models.Model):
    'Displayable API Element'

    name = models.CharField(max_length=64)
    description= models.CharField(max_length=256, blank=True, default='')
    namespace = models.ForeignKey(Namespace, blank=True, null=True)

    section = models.ForeignKey(Section)
    fullname = models.CharField(max_length=128)
    keywords = models.CharField(max_length=256, blank=True, default='')
    data = models.TextField(blank=True, default='')

    source_file = models.CharField(max_length=128, blank=True, null=True)
    source_format = models.CharField(max_length=32, blank=True, null=True)
    
    class Meta:
        verbose_name = "Rendered Element"
        verbose_name_plural = "Rendered Elements"
        ordering = ('name',)

    def __unicode__(self):
        return u'%s' % self.fullname

    @property
    def platform_section(self):
        return self.section


class Page(models.Model):
    'Displayable Page of non-Element content'

    slug = models.CharField(max_length=64)
    title = models.CharField(max_length=64)
    description= models.CharField(max_length=256, blank=True, default='')
    namespace = models.ForeignKey(Namespace, blank=True, null=True)

    section = models.ForeignKey(Section)
    fullname = models.CharField(max_length=128)
    keywords = models.CharField(max_length=256, blank=True, default='')
    data = models.TextField(blank=True, default='')

    source_file = models.CharField(max_length=128, blank=True, null=True)
    source_format = models.CharField(max_length=32, blank=True, null=True)
    order_index = models.PositiveIntegerField(blank=True, null=False, default=0)
    
    class Meta:
        verbose_name = "Rendered Page"
        verbose_name_plural = "Rendered Pages"
        ordering = ('order_index',)

    def __unicode__(self):
        return u'%s' % self.fullname

api_docs/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.template import RequestContext
from django.contrib.auth.models import User, Group

from .models import Topic, Language, Version, Section, Namespace, Element, Page

def _get_release_version(topic_name, language_name, release_version):
    try:
        language = Language.objects.get(topic__slug=topic_name, slug=language_name)
        if release_version == 'current':
            if language is not None and language.current_version is not None:
                version = language.current_version
                return version
        elif release_version == 'development':
            if language is not None and language.development_version is not None:
                version = language.development_version
                return version
    except:
        pass

    return get_object_or_404(Version, language__topic__slug=topic_name, language__slug=language_name, slug=release_version)
    

def overview(request):
    topics = Topic.objects.all()

    context = {
        'topics': topics,
    }
    return render_to_response('api_docs/overview.html', context, RequestContext(request))


def topic_view(request, topic_name):
    topic = get_object_or_404(Topic, slug=topic_name)

    context = {
        'topic': topic,
    }
    return render_to_response('api_docs/topic.html', context, RequestContext(request))


def language_view(request, topic_name, language_name):
    language = get_object_or_404(Language, topic__slug=topic_name, slug=language_name)

    context = {
        'topic': language.topic,
        'language': language,
    }
    return render_to_response('api_docs/language.html', context, RequestContext(request))

from django.forms import ModelForm
class VersionForm(ModelForm):
    class Meta:
        model = Version
        fields = ['name', 'slug']

def release_version(request, topic_name, language_name):
    language = get_object_or_404(Language, topic__slug=topic_name, slug=language_name)

    version = Version(language=language)

    if request.method == 'POST':
        form = VersionForm(request.POST, instance=version)
        if form.is_valid():
            form.save()
            language.current_version = language.development_version
            language.development_version = version
            language.save()
            version.import_from(language.current_version)
            version.save()
            return HttpResponseRedirect(reverse('api_docs:version', args=[topic_name, language_name, version.slug]))
    else:
        form = VersionForm(instance=version)
        
    context = {
        'form': form,
        'topic': language.topic,
        'language': language,
        'version': version,
        'previous': language.development_version,
    }
    return render_to_response('api_docs/version_edit.html', context, RequestContext(request))

def version_view(request, topic_name, language_name, release_version):
    version = _get_release_version(topic_name, language_name, release_version)

    sections = version.section_set.all()
    first_column = []
    second_column = []
    if len(sections) > 1:
        total_size = 0
        sorted_sections = []
        for section in sections:
            section_count = section.namespace_set.count()
            section_count += section.free_element_set().count()
            section_count += section.free_page_set().count()
            if section_count == 0 and not request.user.has_perm('common.change_version'):
                continue
            total_size += section_count + 2 # Extra 2 for the section header
            i = 0
            for s in sorted_sections:
                if (s.namespace_set.count() + s.free_element_set().count()) > section_count:
                    i += 1
                else:
                    break
            sorted_sections.insert(i, section)

        first_column_size = 0
        for section in sorted_sections:
            section_size = section.namespace_set.count() + section.free_element_set().count() + section.free_page_set().count() + 2  # Extra 2 for the section header
            if (first_column_size + section_size) <= (total_size / 2):
                first_column.append(section)
                first_column_size += (section_size)
            else:
                second_column.append(section)
    elif len(sections) == 1:
        first_column.append(sections[0])
        
    context = {
        'sidenav': topic_name,
        'topic': version.language.topic,
        'language': version.language,
        'version': version,
        'first_column': first_column,
        'second_column': second_column,
    }
    return render_to_response('api_docs/version.html', context, RequestContext(request))


def namespace_view(request, topic_name, language_name, release_version, namespace_name):
    version = _get_release_version(topic_name, language_name, release_version)
    
    try:
        namespace = Namespace.objects.get(platform_section__topic_version=version, name=namespace_name)
    except Namespace.MultipleObjectsReturned:
        namespace = Namespace.objects.filter(platform_section__topic_version=version, name=namespace_name)[0]
    except Namespace.DoesNotExist:
        return page_view(request, topic_name, language_name, release_version, namespace_name)

    context = {
        'sidenav': topic_name,
        'topic': version.language.topic,
        'language': version.language,
        'version': version,
        'namespace': namespace,
    }
    return render_to_response('api_docs/namespace.html', context, RequestContext(request))


def page_view(request, topic_name, language_name, release_version, page_fullname):
    version = _get_release_version(topic_name, language_name, release_version)

    page = get_object_or_404(Page, section__topic_version=version, fullname=page_fullname)

    context = {
        'sidenav': topic_name,
        'topic': version.language.topic,
        'language': version.language,
        'version': version,
        'page': page,
    }
    return render_to_response('api_docs/page.html', context, RequestContext(request))


def element_view(request, topic_name, language_name, release_version, element_fullname):
    version = _get_release_version(topic_name, language_name, release_version)

    try:
        element = Element.objects.get(section__topic_version=version, fullname=element_fullname)
    except Element.MultipleObjectsReturned:
        element = Element.objects.filter(section__topic_version=version, fullname=element_fullname)[0]
    except Element.DoesNotExist:
        return namespace_view(request, topic_name, language_name, release_version, element_fullname)

    context = {
        'sidenav': topic_name,
        'topic': version.language.topic,
        'language': version.language,
        'version': version,
        'element': element,
    }
    return render_to_response('api_docs/element.html', context, RequestContext(request))

api_docs/templates/api_docs/article.html
{% extends "base.html" %}


{% block content %}
	<div class="row">
		<div class="ten-col">
	{% block article_content %}
	{% endblock %}
		</div>
	</div>
{% endblock %}

api_docs/templates/api_docs/delete_confirm.html
{% extends "api_docs/article.html" %}

{% block editor_links %}
    <li><a href="?action=delete_cancel">Cancel</a></li>
{% endblock %}

{% block breadcrumbs %}
{% endblock %}

{% block article_content %}
<h1>Delete: {{name}}</h1>

Are you sure that you want to delete this {{type}}?

<form action="?action=delete_confirm" method="GET" id="delete_form">
{% csrf_token %}
<div id="element_content">
<input type="hidden" name="action" value="delete_confirm" />
</div>
<input type="submit" value="Confirm">
</form>

{% endblock %}

api_docs/templates/api_docs/element_edit.html
{% extends "api_docs/article.html" %}

{% block editor_links %}
	{% if element.id and perms.apidocs.delete_element %}
    <li><a href="{% url element_edit topic.slug version.slug element.id %}?action=delete">Delete</a></li>
    {% endif %}
{% endblock %}

{% block breadcrumbs %}
{% endblock %}

{% block article_content %}
{% if element.id %}
<h1>Edit: {{element.name}}</h1>
{% else %}
<h1>New Element</h1>
{% endif %}

<form action="" method="POST" id="element_form">
{% csrf_token %}
<div id="element_content">
{{ form.as_p }}
</div>
<input type="submit" value="Save">
</form>

{% comment %}
<h3>Snippets</h3>
{% for snippet in snippets %}
    <div>
        <li>{{ snippet.name }}</li>
    </div>
{% endfor %}

<h3>Questions & Answers</h3>
{% for question in questions %}
    <div>
        <li><a href="{{ question.url }}">{{ question.name }}</a></li>
    </div>
{% endfor %}
<h3>Tutorials</h3>
{% for tutorial in tutorials %}
    <div>
        <li><a href="{{ tutorial.url }}">{{ tutorial.name }}</a></li>
    </div>
{% endfor %}
{% endcomment %}
{% endblock %}

api_docs/templates/api_docs/language_edit.html
{% extends "api_docs/base.html" %}

{% block sub_nav %}{% endblock %}

{% block content %}

{% if language.id %}
<h2>Edit: {{language.name}}</h2>
{% else %}
<h2>New Language</h2>
{% endif %}

<form action="" method="POST" id="language_form">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Save">
</form>
{% endblock %}

api_docs/templates/api_docs/namespace.html
{% extends "api_docs/article.html" %}
{% load static %}

{% block title %}{{namespace.name}} [{{version.slug}}/{{namespace.name}}] | {{ block.super }}{% endblock %}

{% block extrastyles %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" media="all" href="{% static 'api_docs/css/' %}{{namespace.source_format}}.css"/>
{% endblock extrastyles %}

{% block editor_links %}
    {% if perms.apidocs.change_namespace %}
    <li><a href="{% url 'api_docs:namespace_edit' version.language.topic.slug version.language.slug version.slug namespace.id%}">Edit</a></li>
    {% endif %}
    {% if perms.apidocs.add_element %}
    <li><a href="{% url 'api_docs:element_edit' version.language.topic.slug version.language.slug version.slug %}">+ Element</a></li>
    {% endif %}
    {% if perms.apidocs.add_page %}
    <li><a href="{% url 'api_docs:page_edit' version.language.topic.slug version.language.slug version.slug %}">+ Page</a></li>
    {% endif %}
{% endblock %}

{% block breadcrumb_links %}
<li class=""><a href="{% url 'api_docs:overview' %}">APIs</a> &rsaquo;</li>
<li class=""><a href="{% url 'api_docs:topic' version.language.topic.slug %}">{{version.language.topic.name}}</a> &rsaquo;</li>
<li class=""><a href="{% url 'api_docs:language' version.language.topic.slug version.language.slug %}">{{version.language.name}}</a> &rsaquo;</li>
<li><a class="sub-nav-item" href="{% url 'api_docs:version' version.language.topic.slug version.language.slug version.slug %}">{{version.name}}</a> &rsaquo;</li>
<li>{{namespace.name}}</li>
{% endblock %}

{% block content %}
<!-- Source File: {{element.source_file}} -->
<!-- Source Format: {{element.source_format}} -->

{% if namespace.data %}
<div id="namespace_content" class="row {{namespace.source_format}}">
    <div class="ten-col">
        <h2>{{namespace.name}}</h2>

        <!-- Start Namespace Content -->
        {{namespace.data|safe}}
        <!-- End Namespace Content -->
    </div>
</div>
{% endif %}
<div id="namespace_content" class="row {{namespace.source_format}}">

    {% if namespace.element_set.count %}
    <div class="eight-col">
    <h3>Elements</h3>
    <dl>
    {% for element in namespace.element_set.all %}
        <dt><a href="{% url 'api_docs:element' version.language.topic.slug version.language.slug version.slug element.fullname %}">{{element.name}}</a></dt><dd>{{ element.description|safe }}</dd>
    {% endfor %}
    </dl>
    </div>
    {% endif %}

    {% if namespace.page_set.count %}
    <div class="four-col last-col">
    <h3>Pages</h3>
    <ul>
    {% for page in namespace.page_set.all %}
        <li><a href="{% url 'api_docs:element' version.language.topic.slug version.language.slug version.slug page.fullname %}">{{page.title}}</a></li>
    {% endfor %}
    </ul>
    </div>
    {% endif %}


</div>

{% endblock %}

api_docs/templates/api_docs/namespace_edit.html
{% extends "api_docs/article.html" %}

{% block editor_links %}
	{% if namespace.id and perms.apidocs.delete_namespace %}
    <li><a href="{% url namespace_edit topic.slug version.slug namespace.id %}?action=delete">Delete</a></li>
    {% endif %}
{% endblock %}

{% block breadcrumbs %}
{% endblock %}

{% block article_content %}
{% if namespace.id %}
<h1>Edit: {{namespace.name}}</h1>
{% else %}
<h1>New Namespace</h1>
{% endif %}

<form action="" method="POST" id="namespace_form">
{% csrf_token %}
<div id="namespace_content">
{{ form.as_p }}
</div>
<input type="submit" value="Save">
</form>

{% comment %}
<h3>Snippets</h3>
{% for snippet in snippets %}
    <div>
        <li>{{ snippet.name }}</li>
    </div>
{% endfor %}

<h3>Questions & Answers</h3>
{% for question in questions %}
    <div>
        <li><a href="{{ question.url }}">{{ question.name }}</a></li>
    </div>
{% endfor %}
<h3>Tutorials</h3>
{% for tutorial in tutorials %}
    <div>
        <li><a href="{{ tutorial.url }}">{{ tutorial.name }}</a></li>
    </div>
{% endfor %}
{% endcomment %}
{% endblock %}

api_docs/templates/api_docs/overview.html
{% extends "base.html" %}

{% block sub_nav %}{% endblock %}

{% block breadcrumb_links %}
<li class="">APIs</li>
{% endblock %}

{% block content %}
<div class="row">
<h2>Topics</h2>
<ul>
{% for topic in topics %}
    <li><a href="{% url 'api_docs:topic' topic.slug %}">{{topic.name}}</a></li>
{% endfor %}
</ul>
</div>
{% endblock %}

api_docs/templates/api_docs/page.html
{% extends "api_docs/article.html" %}
{% load static %}

{% block title %}{{ page.title }} | {{ block.super }}{% endblock title%}

{% block extrastyles %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" media="all" href="{% static 'api_docs/css/' %}{{page.source_format}}.css"/>
{% endblock extrastyles %}

{% block editor_links %}
    {% if perms.apidocs.change_page %}
    <li><a href="{% url 'api_docs:page_edit' topic.slug version.language.slug version.slug page.id %}">Edit</a></li>
    {% endif %}
    {% if perms.apidocs.delete_page %}
    <li><a href="{% url 'api_docs:page_edit' topic.slug version.language.slug version.slug page.id %}?action=delete">Delete</a></li>
    {% endif %}
{% endblock %}

{% block breadcrumb_links %}
<li class=""><a href="{% url 'api_docs:overview' %}">APIs</a> &rsaquo;</li>
<li class=""><a href="{% url 'api_docs:topic' version.language.topic.slug %}">{{version.language.topic.name}}</a> &rsaquo;</li>
<li class=""><a href="{% url 'api_docs:language' version.language.topic.slug version.language.slug %}">{{version.language.name}}</a> &rsaquo;</li>
<li><a class="sub-nav-item" href="{% url 'api_docs:version' version.language.topic.slug version.language.slug version.slug %}">{{version.name}}</a> &rsaquo;</li>
{% if page.namespace %}
<li><a class="sub-nav-item" href="{% url 'api_docs:element' topic.slug version.language.slug version.slug page.namespace.name %}">{{page.namespace.name}}</a> &rsaquo;</li>
{% endif %}
{% endblock %}

{% block second_level_nav_links %}
<li class="active">{{page.title}}</li>
{% endblock %}

{% block article_content %}
	<!-- Source File: {{page.source_file}} -->
	<!-- Source Format: {{page.source_format}} -->
<h1>{{page.title}}</h1>
<div id="page_content" class="{{page.source_format}}">
<!-- Start Element Content -->
{{page.data|safe}}
<!-- End Element Content -->
</div>

{% endblock %}

api_docs/templates/api_docs/page_edit.html
{% extends "api_docs/article.html" %}

{% block editor_links %}
	{% if page.id and perms.apidocs.delete_page %}
    <li><a href="{% url page_edit topic.slug version.slug page.id %}?action=delete">Delete</a></li>
    {% endif %}
{% endblock %}

{% block breadcrumbs %}
{% endblock %}

{% block article_content %}
{% if page.id %}
<h2>Edit {{page.name}}</h2>
{% else %}
<h2>New Page</h2>
{% endif %}

<form action="" method="POST" id="page_form">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Save">
</form>

{% endblock %}

api_docs/templates/api_docs/section_edit.html
{% extends "api_docs/article.html" %}

{% block editor_links %}
	{% if section.id and perms.common.delete_section %}
    <li><a href="{% url section_edit topic.slug language.slug version.slug section.id %}?action=delete">Delete</a></li>
    {% endif %}
{% endblock %}

{% block breadcrumbs %}
{% endblock %}

{% block article_content %}
{% if section.id %}
<h2>Edit {{section.name}}</h2>
{% else %}
<h2>New Section</h2>
{% endif %}

<form action="" method="POST" id="section_form">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Save">
</form>

{% endblock %}

api_docs/templates/api_docs/token_edit.html
{% extends "base.html" %}

{% block sub_nav %}{% endblock %}

{% block content %}

<table width="100%">
<tr><th>User</th><th>Token</th><th>Actions</th></tr>
{% for t in tokens %}
<tr>
    <td>{{t.user.username}}</td>
    <td>{{t.key}}</td>
    <td>
        <a href="{% url 'api_docs:token_edit' t.key %}?action=reset">Reset</a> | 
        <a href="{% url 'api_docs:token_edit' t.key %}?action=delete">Delete</a>
    </td>
</tr>
{% endfor %}
</table>

<table width="100%">
<tr><td width="50%" style="vertical-align: top; text-align: left; border: 0;">

<h2>Generate Token</h2>
<form action="{% url 'api_docs:token_edit' %}" method="POST" id="token_form">
{% csrf_token %}
<input type="hidden" name="form" value="token"/>
{{ form.as_p }}
<input type="submit" value="Generate">
</form>

</td><td width="50%" style="vertical-align: top; text-align: left; border: 0;">

<h2>Add User</h2>
<form action="{% url 'api_docs:token_edit' %}" method="POST" id="user_form">
{% csrf_token %}
<input type="hidden" name="form" value="user"/>
{{ adduser.as_p }}
<input type="submit" value="Add">
</form>

</td></tr></table>
{% endblock %}

api_docs/templates/api_docs/topic.html
{% extends "base.html" %}

{% block sub_nav %}{% endblock %}

{% block breadcrumb_links %}
<li class=""><a href="{% url 'api_docs:overview' %}">APIs</a> &rsaquo;</li>
<li class="">{{topic.name}}</li>
{% endblock %}

{% block content %}
<div class="row">
<h2>{{topic.name}} Languages</h2>
<ul>
{% for language in topic.language_set.all %}
    <li>
        <a href="{% url 'api_docs:language' topic.slug language.slug %}">{{language.name}}</a>
    </li>
{% endfor %}
</ul>
</div>
{% endblock %}

api_docs/templates/api_docs/topic_edit.html
{% extends "api_docs/base.html" %}

{% block sub_nav %}{% endblock %}

{% block content %}

{% if topic.id %}
<h2>Edit: {{topic.name}}</h2>
{% else %}
<h2>New Topic</h2>
{% endif %}

<form action="" method="POST" id="topic_form">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Save">
</form>
{% endblock %}